import { Article } from './article.model';

export const ARTICLES: Array<Article> = [
  {
    id: 201,
    name: 'Nulla',
    price: 207,
    description: 'You really want to know what Nulla is?',
    category: 'Food',
    review: 78,
  },
  {
    id: 202,
    name: 'Corporis',
    price: 271,
    description: 'You really want to know what Corporis is?',
    category: 'Clothing',
    review: 67,
  },
  {
    id: 203,
    name: 'Minus',
    price: 295,
    description: 'You really want to know what Minus is?',
    category: 'Food',
    review: 116,
  },
  {
    id: 204,
    name: 'Qui',
    price: 280,
    description: 'You really want to know what Qui is?',
    category: 'Food',
    review: 78,
  },
  {
    id: 206,
    name: 'Est',
    price: 296,
    description: 'You really want to know what Est is?',
    category: 'Clothing',
    review: 107,
  },
  {
    id: 208,
    name: 'Ratione',
    price: 104,
    description: 'You really want to know what Ratione is?',
    category: 'Cosmetic',
    review: 104,
  },
  {
    id: 209,
    name: 'Similique',
    price: 262,
    description: 'You really want to know what Similique is?',
    category: 'Clothing',
    review: 44,
  },
  {
    id: 210,
    name: 'Molestias',
    price: 145,
    description: 'You really want to know what Molestias is?',
    category: 'Food',
    review: 95,
  },
  {
    id: 211,
    name: 'Modi',
    price: 228,
    description: 'You really want to know what Modi is?',
    category: 'Cosmetic',
    review: 153,
  },
  {
    id: 212,
    name: 'Voluptatibus',
    price: 172,
    description: 'You really want to know what Voluptatibus is?',
    category: 'Food',
    review: 29,
  },
  {
    id: 213,
    name: 'Sapiente',
    price: 100,
    description: 'You really want to know what Sapiente is?',
    category: 'Cosmetic',
    review: 200,
  },
  {
    id: 214,
    name: 'Alias',
    price: 152,
    description: 'You really want to know what Alias is?',
    category: 'Clothing',
    review: 68,
  },
  {
    id: 215,
    name: 'Non',
    price: 189,
    description: 'You really want to know what Non is?',
    category: 'Food',
    review: 86,
  },
  {
    id: 216,
    name: 'Quaerat',
    price: 280,
    description: 'You really want to know what Quaerat is?',
    category: 'Food',
    review: 135,
  },
];
