language: node_js
node_js: "10"
sudo: true

addons:
  chrome: stable

install:
  - npm ci

script:
  - npm run lint
  - npm run build ngx-matomo
  - npm run test-headless ngx-matomo
  - npm run test-headless demo
