name: Node CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ['14']

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install, lint, build, and test
        run: |
          npm ci
          npm run lint
          npm run build ngx-matomo
          npm run test:ci ngx-matomo
          npm run test:ci demo
        env:
          CI: true
